CREATE TABLE  EXPORTACIONES
("ID" NUMBER, 
"ANIO" NUMBER, 
"MES" VARCHAR2(100), 
"CODIGOPAIS" NUMBER, 
"PAISDESTINO" VARCHAR2(100), 
"CODIGODEPTO" NUMBER(20,5), 
"DEPARTAMENTOORIGEN" VARCHAR2(100), 
"PARTIDA" VARCHAR2(300),
"CADENA" VARCHAR2(100), 
"PRODUCTO" VARCHAR2(100),
"CODIGOUNIDAD" VARCHAR2(10),
"CANTIDADUNIDADES" NUMBER,
"VALORMILESFOBDOL" NUMBER,
"VALORMILESPESOS" NUMBER,
"VOLUMENTONELADAS" NUMBER
)
/