CREATE TABLE  "HOTELESDORADA" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(50), 
	"DIRECCION" VARCHAR2(50), 
	"BARRIO" VARCHAR2(50), 
	"TELEFONO" VARCHAR2(40), 
	"CANTIDADCAMAS" NUMBER, 
	"CANTIDADHABITACIONES" NUMBER, 
	"PISCINA" VARCHAR2(50), 
	"ADMINISTRADOR" VARCHAR2(255), 
	"TELEFONO2" VARCHAR2(40)
   )
/