--SE DEBE EVIDENCIAR EL PORCENTAJE DE ESTUDIANTES QUE HAN CURSADO CADA CURSO, EN CADA GRADO, CON RESPECTO A LA CANTIDAD
--TOTAL DE ESTUDIANTES MATRICULADOS EN EL CURSO

--IS SELECT NCURSO,DEPARTAMENTO,COUNT(*) FROM MATRICULAS GROUP BY DEPARTAMENTO,NCURSO
--HAVING NCURSO='101' AND DEPARTAMENTO='HIS';

SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE PUNTO_5

AS
    --UN CURSOR PARA EN EL CUAL SE OBTIENE LA CANTIDAD DE MATRICULADOS POR CURSO
    CURSOR CONTADOR_ESTUDIANTES IS SELECT GRADO,NCURSO,DEPARTAMENTO,COUNT(*) AS CANTIDAD FROM MATRICULAS
    GROUP BY GRADO,NCURSO,DEPARTAMENTO HAVING GRADO IN('B','C') ORDER BY GRADO;
    
    --El porcentaje a calcular en cada iteración:
    PORCENTAJE NUMBER:=0;
    
    TOTAL_CONSULTA NUMBER:=0;
    
    DESCRIPCIONCUR VARCHAR2(40);

BEGIN

    
    DBMS_OUTPUT.PUT_LINE('GRADO     CURSO       DESCRIPCION     PORCENTAJE');
    
    --SE RECORRE EL CURSOR PARA IR OBTENIENDO EL CALCULO DE EL PORCENTAJE CON RESPECTO A LOS ESTUDIANTES POR CURSO:
    FOR REGISTRO IN CONTADOR_ESTUDIANTES
    LOOP
        
        --OBTENIENDO EL TOTAL DE ESTUDIANTES MATRICULADOS EN ESE CURSO:
        SELECT COUNT(*) INTO TOTAL_CONSULTA FROM MATRICULAS
        GROUP BY DEPARTAMENTO,NCURSO
        HAVING NCURSO=REGISTRO.NCURSO AND DEPARTAMENTO=REGISTRO.DEPARTAMENTO;
        
        --SE OBTIENE LA DESCRIPCION PARA EL CURSO QUE SE ESTÁ ANALIZANDO:
        SELECT DISTINCT DESCRIPCIONCURSO INTO DESCRIPCIONCUR FROM MATRICULAS MAT JOIN CURSOS CUR ON
        MAT.NCURSO=CUR.NCURSO AND MAT.DEPARTAMENTO=CUR.DEPARTAMENTO
        WHERE CUR.departamento=REGISTRO.DEPARTAMENTO AND CUR.NCURSO=REGISTRO.NCURSO;
        
        --SE CALCULA EL PORCENTAJE:
        PORCENTAJE:= ROUND((REGISTRO.CANTIDAD*100)/TOTAL_CONSULTA,3);
        
        DBMS_OUTPUT.PUT_LINE('HOLA');
        --SE MUESTRA LA INFORMACION CALCULADA
        DBMS_OUTPUT.PUT_LINE(REGISTRO.GRADO||'      '||REGISTRO.NCURSO||'       '||DESCRIPCIONCUR||'      '||PORCENTAJE);
        
    END LOOP;


EXCEPTION

    WHEN OTHERS THEN
    
        NULL;

END;
/
SHOW ERRORS;


EXECUTE PUNTO_5();